# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e22fae3b073091f81833f17a4a8fcb1a0ab4bfdbf90d97c8f2bfa38e4516f3403a0721b2dee92feea2f665b9eae66850d8ae542ad682eb26b2017dbd8f0d4ebc

test:
  secret_key_base: e69140134a7a26f83f54b9b9a55570d526316705746784e0ebd55c42151150ae5fa39bc9db9eca7ce02d3981fc0740908c2d2ea8816e41c7f04fe9ab911fc6d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
